### ISSUE TITLE
This bricked my partition table

### ISSUE THREAD

**Issue by eknight91** [devchilly/RISKHackTool#1]
Looks like malware … good joke but please keep my nudes to yourself if you took any of my data.     The code looks nice and legit so it makes me wonder if it’s just a (very bad) bug… but after reading some of the things this user has said over the internet it makes me think it’s likely some weird sick joke.   

Can you tell me why my PC might randomly hard reset and partition table might disappear after running the executable?   Or is it supposed to do this?

**Comment by devchilly** [comment]
@eknight91 This is a lie lol you even tried to troll my youtube video

**Comment by Tweacked** [comment]
Dose look like mal
